language: bash

jobs:
  include:
    - stage: before_deploy
      name: "Push to ECR"
      script: ./scripts/push-image
      if: type = push AND branch = master
      env:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
        - ES_URL=${ES_URL}

    - stage: deploy
      name: "Deploy ECS service"
      script: ./scripts/deploy-ecs
      if: type = push AND branch = master
