language: bash

before_deploy:
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip > /dev/null ; sudo ./aws/install ; fi
  - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 572269113430.dkr.ecr.ap-southeast-2.amazonaws.com
  - docker build --build-arg ES_URL=${ES_URL} -t parking-sensor-api:${TRAVIS_BUILD_NUMBER} .
  - docker push parking-sensor-api:${TRAVIS_BUILD_NUMBER}

deploy:
  - echo "Deploy"

jobs:
  include:
    - name: "Push to ECR"
      if: type = push AND branch = master
      env:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
