#! /bin/bash
set -e

if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip > /dev/null ; sudo ./aws/install ; fi
aws configure set default.region ap-southeast-2
aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 972517480395.dkr.ecr.ap-southeast-2.amazonaws.com
docker build --build-arg ES_URL=$ES_URL -t 972517480395.dkr.ecr.ap-southeast-2.amazonaws.com/parking-sensor-api:$TRAVIS_BUILD_NUMBER .
aws ecr describe-repositories --repository-names parking-sensor-api || aws ecr create-repository --repository-name parking-sensor-api
docker push 972517480395.dkr.ecr.ap-southeast-2.amazonaws.com/parking-sensor-api:$TRAVIS_BUILD_NUMBER
